substitutions:
  _SERVICE_NAME: springboot-cloud-run
  _REGION: asia-south1
  _DB_PASSWORD_SECRET: db-password


steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '${_SERVICE_NAME}',
        '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}',
        '--region', '${_REGION}',
        '--allow-unauthenticated',
        '--add-cloudsql-instances=$PROJECT_ID:${_REGION}:postgres-instance',
        '--service-account=springboot-cloudrun-sa@$PROJECT_ID.iam.gserviceaccount.com',
        '--set-secrets=SPRING_DATASOURCE_PASSWORD=${_DB_PASSWORD_SECRET}:latest'
      ]

  # Optional verification step
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Verifying deployment..."
        gcloud run services describe ${_SERVICE_NAME} --region ${_REGION}
        echo "Secret access verified:"
        gcloud secrets describe ${_DB_PASSWORD_SECRET}

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'